# Generated by Django 3.1.1 on 2020-09-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barre_code', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=300)),
                ('nutriscode', models.CharField(max_length=1)),
            ],
        ),
    ]
