# Generated by Django 3.1.1 on 2020-09-28 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products_app', '0002_auto_20200925_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
    ]
