# Generated by Django 3.1.1 on 2020-09-28 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products_app', '0005_auto_20200928_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='energy_kcal',
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='energy_kj',
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='fiber',
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='glucid',
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='lipid',
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt',
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
