# Generated by Django 3.1.1 on 2020-09-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products_app', '0006_auto_20200928_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='energy_kcal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='energy_kj',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='fiber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='glucid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='lipid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt',
            field=models.CharField(max_length=50),
        ),
    ]
