# Generated by Django 3.1.1 on 2020-09-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tartampion',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
