product_complete = {
    'products': [{
        "product_name_de_debug_tags": [],
        "product_name_en": "Eau Cristaline",
        "generic_name_fr": "Eau de source naturelle",
        "nutrition_grade_fr": "a",
        "data_quality_warnings_tags": [
            "en:nutrition-value-under-0-1-g-salt",
            "en:nutrition-value-very-high-for-category-fat"
        ],
        "minerals_prev_tags": [],
        "url": "https://fr.openfoodfacts.org/produit/3274080005003/eau-de-source-cristalline",
        "image_ingredients_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/ingredients_fr.549.400.jpg",
        "nova_group_tags": [
            "not-applicable"
        ],
        "nutrition_data_prepared_per": "100g",
        "allergens_lc": "fr",
        "amino_acids_tags": [],
        "languages_hierarchy": [
            "en:english",
            "en:french",
            "en:italian"
        ],
        "traces_from_ingredients": "",
        "ingredients_text_with_allergens": "Eau de source.",
        "image_ingredients_small_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/ingredients_fr.549.200.jpg",
        "purchase_places_tags": [
            "france",
            "rennes",
            "chinon",
            "blagnac"
        ],
        "nova_group_debug": "",
        "ingredients_ids_debug": [
            "eau-de-source"
        ],
        "last_checker": "sebleouf",
        "origins_tags": [
            "france"
        ],
        "brands_tags": [
            "cristalline"
        ],
        "labels_hierarchy": [
            "fr:Sans-nitrate"
        ],
        "generic_name_de": "",
        "unique_scans_n": 6482,
        "known_ingredients_n": 2,
        "product_name_it": "Acqua di sorgente",
        "environment_impact_level_tags": [],
        "_id": "3274080005003",
        "nutrition_score_beverage": 1,
        "ingredients_text_fr": "Eau de source.",
        "entry_dates_tags": [
            "2012-07-28",
            "2012-07",
            "2012"
        ],
        "nova_groups_tags": [
            "en:1-unprocessed-or-minimally-processed-foods"
        ],
        "obsolete_since_date": "",
        "ingredients_text_de": "",
        "max_imgid": "313",
        "unknown_ingredients_n": 0,
        "nutrition_grades_tags": [
            "a"
        ],
        "photographers": [],
        "link": "https://www.moneaucristaline.fr/",
        "additives_old_n": 0,
        "ingredients_text": "Eau de source.",
        "nucleotides_prev_tags": [],
        "ingredients": [
            {
                "percent_min": 100,
                "vegan": "yes",
                "vegetarian": "yes",
                "id": "en:spring-water",
                "text": "Eau de source",
                "rank": 1,
                "percent_max": 100
            }
        ],
        "image_front_small_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.200.jpg",
        "ingredients_text_de_debug_tags": [],
        "scans_n": 10501,
        "fruits-vegetables-nuts_100g_estimate": 0,
        "completed_t": 1600699839,
        "update_key": "ingredients3",
        "informers": [
            "sientifix"
        ],
        "checkers_tags": [
            "sebleouf"
        ],
        "misc_tags": [
            "en:nutrition-fruits-vegetables-nuts-estimate-from-ingredients",
            "en:nutrition-all-nutriscore-values-known",
            "en:nutriscore-computed"
        ],
        "product_name_fr": "Eau de source",
        "nutrition_data_prepared": "",
        "ingredients_percent_analysis": 1,
        "countries": "Belgique,France,Allemagne,Guadeloupe,Inde,Italie,Luxembourg,Mali,Martinique,Pays-Bas,Suisse,États-Unis,Royaume-Uni",
        "last_checked_t": 1600699839,
        "emb_codes_orig": "EMB 44068A,EMB 59457",
        "ingredients_from_or_that_may_be_from_palm_oil_n": 0,
        "emb_codes_20141016": "EMB 44068A,EMB 59457",
        "allergens_from_user": "(fr) ",
        "data_quality_bugs_tags": [],
        "emb_codes": "EMB 44068A,EMB 59457,EMB 72007B",
        "generic_name_en": "",
        "ingredients_debug": [
            "Eau de source."
        ],
        "countries_lc": "fr",
        "ingredients_that_may_be_from_palm_oil_tags": [],
        "rev": 593,
        "states": "en:checked, en:complete, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-completed, en:packaging-code-completed, en:characteristics-completed, en:categories-completed, en:brands-completed, en:packaging-completed, en:quantity-completed, en:product-name-completed, en:photos-validated, en:photos-uploaded",
        "ingredients_text_debug": "Eau de source.",
        "nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients_value": 0,
        "unknown_nutrients_tags": [
            "sulfate",
            "nitrate"
        ],
        "last_editor": "sebleouf",
        "expiration_date": "23/10/21",
        "quantity": "1,5 L",
        "labels_lc": "fr",
        "data_sources": "Database - FoodRepo / openfood.ch, Databases, App - labeleat, App - off, App - yuka, Apps",
        "additives_n": 0,
        "image_nutrition_small_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/nutrition_fr.591.200.jpg",
        "data_quality_info_tags": [
            "en:ingredients-percent-analysis-ok"
        ],
        "countries_beforescanbot": "Belgique,France,Allemagne,Guadeloupe,Inde,Italie,Luxembourg,Mali,Martinique,Suisse,États-Unis",
        "ingredients_text_with_allergens_it": "Acqua",
        "packaging": "01 PET,♳,Bouteille,Plastique",
        "popularity_key": 119999996494,
        "nutriments": {
            "nitrate_unit": "mg",
            "silica_unit": "mg",
            "fluoride_100g": 0.0003,
            "silica": 0.026,
            "nutrition-score-fr_100g": 0,
            "chloride_value": 5,
            "fiber": 0,
            "calcium_label": "Calcium",
            "energy-kj_100g": 0,
            "fiber_unit": "g",
            "sulfate_unit": "mg",
            "sulfate_label": "Sulfate",
            "salt": 0.0275,
            "silica_label": "Silice",
            "energy_unit": "kJ",
            "nitrate_value": 1,
            "ph_label": "pH",
            "energy-kj": 0,
            "saturated-fat_unit": "g",
            "bicarbonate_100g": 0.29,
            "potassium_100g": 0.0015,
            "fiber_value": 0,
            "magnesium_100g": 0.025,
            "bicarbonate_unit": "mg",
            "salt_100g": 0.0275,
            "sulfate": 0.006,
            "ph_value": 7.7,
            "calcium_value": 39,
            "chloride_unit": "mg",
            "salt_value": 0.0275,
            "sugars": 0,
            "saturated-fat_100g": 0,
            "fat": 4,
            "nitrate_label": "Nitrate",
            "energy_100g": 0,
            "nutrition-score-fr": 0,
            "potassium_unit": "mg",
            "nova-group": 1,
            "sodium": 0.011,
            "sodium_unit": "g",
            "energy-kcal_100g": 0,
            "bicarbonate_label": "Bicarbonate",
            "nova-group_serving": 1,
            "ph": 7.7,
            "fluoride": 0.0003,
            "carbohydrates_value": 0,
            "nitrate_100g": 0.001,
            "chloride": 0.005,
            "calcium_100g": 0.039,
            "nitrate": 0.001,
            "carbohydrates": 0,
            "fiber_100g": 0,
            "bicarbonate": 0.29,
            "fluoride_value": 0.3,
            "carbohydrates_unit": "g",
            "sulfate_100g": 0.006,
            "sodium_100g": 0.011,
            "proteins": 0,
            "proteins_100g": 0,
            "energy-kcal_value": 0,
            "sugars_unit": "g",
            "calcium": 0.039,
            "calcium_unit": "mg",
            "silica_100g": 0.026,
            "energy-kcal": 0,
            "carbohydrates_100g": 0,
            "ph_serving": 7.7,
            "sodium_value": 0.011,
            "silica_value": 26,
            "chloride_100g": 0.005,
            "energy-kj_unit": "kJ",
            "salt_unit": "g",
            "energy-kcal_unit": "kcal",
            "potassium": 0.0015,
            "sugars_value": 0,
            "fluoride_unit": "mg",
            "potassium_value": 1.5,
            "proteins_value": 0,
            "bicarbonate_value": 290,
            "fat_value": 4,
            "magnesium_unit": "mg",
            "fat_unit": "g",
            "saturated-fat_value": 0,
            "sugars_100g": 0,
            "proteins_unit": "g",
            "sulfate_value": 6,
            "magnesium_value": 25,
            "energy-kj_value": 0,
            "fluoride_label": "Fluor",
            "ph_100g": 7.7,
            "fat_100g": 4,
            "saturated-fat": 0,
            "fruits-vegetables-nuts-estimate-from-ingredients_100g": 0,
            "energy_value": 0,
            "magnesium_label": "Magnésium",
            "nova-group_100g": 1,
            "energy": 0,
            "ph_unit": "g",
            "magnesium": 0.025,
            "potassium_label": "Potassium",
            "chloride_label": "Chlorure"
        },
        "nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients": 1,
        "category_properties": {
            "ciqual_food_name:en": "Spring still water -Cristaline-, bottled",
            "ciqual_food_name:fr": "Eau de source Cristaline, embouteillée, non gazeuse"
        },
        "categories_lc": "fr",
        "stores": "Carrefour,auchan,Leclerc",
        "ingredients_text_en": "water",
        "image_thumb_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.100.jpg",
        "data_quality_tags": [
            "en:ingredients-percent-analysis-ok",
            "en:nutrition-value-under-0-1-g-salt",
            "en:nutrition-value-very-high-for-category-fat"
        ],
        "traces_from_user": "(fr) ",
        "checkers": [],
        "additives_old_tags": [],
        "vitamins_tags": [],
        "ingredients_hierarchy": [
            "en:spring-water",
            "en:water"
        ],
        "categories": "Boissons, Eaux, Eaux de sources, Eaux minérales, Boissons sans sucre ajouté",
        "no_nutrition_data": "",
        "pnns_groups_1_tags": [
            "beverages",
            "known"
        ],
        "additives_original_tags": [],
        "other_nutritional_substances_tags": [],
        "ingredients_tags": [
            "en:spring-water",
            "en:water"
        ],
        "purchase_places": "France,Rennes,Chinon,Blagnac",
        "compared_to_category": "en:unsweetened-beverages",
        "created_t": 1343503270,
        "lang": "fr",
        "cities_tags": [
            "guenrouet-loire-atlantique-france",
            "perenchies-nord-france",
            "ardenay-sur-merize-sarthe-france"
        ],
        "pnns_groups_2_tags": [
            "waters-and-flavored-waters",
            "known"
        ],
        "environment_impact_level": "",
        "nutrition_data_per": "100g",
        "ingredients_from_palm_oil_n": 0,
        "product_name_de": "",
        "allergens_from_ingredients": "",
        "labels_tags": [
            "fr:sans-nitrate"
        ],
        "image_ingredients_thumb_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/ingredients_fr.549.100.jpg",
        "amino_acids_prev_tags": [],
        "origins": "France",
        "allergens_hierarchy": [],
        "generic_name": "Eau de source naturelle",
        "image_nutrition_thumb_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/nutrition_fr.591.100.jpg",
        "lc": "fr",
        "complete": 1,
        "generic_name_it": "Acqua minerale",
        "ingredients_text_it": "Acqua",
        "ingredients_that_may_be_from_palm_oil_n": 0,
        "data_quality_errors_tags": [],
        "interface_version_created": "20120622",
        "labels": "Sans-nitrate",
        "completeness": 1,
        "image_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.400.jpg",
        "traces": "",
        "correctors": [],
        "vitamins_prev_tags": [],
        "ingredients_n": 1,
        "additives_debug_tags": [],
        "manufacturing_places": "France,72370,Ardenay-sur-Merize",
        "nova_group": 1,
        "image_small_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.200.jpg",
        "emb_codes_tags": [
            "emb-44068a",
            "emb-59457",
            "emb-72007b"
        ],
        "id": "3274080005003",
        "stores_tags": [
            "carrefour",
            "auchan",
            "leclerc"
        ],
        "debug_tags": [
            "43"
        ],
        "nutriscore_score": 0,
        "nutrition_data": "on",
        "traces_lc": "fr",
        "image_nutrition_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/nutrition_fr.591.400.jpg",
        "image_front_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.400.jpg",
        "ingredients_text_with_allergens_fr": "Eau de source.",
        "nutriscore_grade": "a",
        "languages": {
            "en:english": 4,
            "en:french": 6,
            "en:italian": 5
        },
        "last_edit_dates_tags": [
            "2020-09-21",
            "2020-09",
            "2020"
        ],
        "nutrient_levels_tags": [
            "en:fat-in-moderate-quantity",
            "en:saturated-fat-in-low-quantity",
            "en:sugars-in-low-quantity",
            "en:salt-in-low-quantity"
        ],
        "minerals_tags": [],
        "ingredients_text_with_allergens_en": "water",
        "allergens": "",
        "obsolete": "",
        "ingredients_original_tags": [
            "en:spring-water"
        ],
        "generic_name_de_debug_tags": [],
        "product_name": "Eau de source",
        "nutrition_grades": "a",
        "last_image_t": 1598513295,
        "additives_tags": [],
        "ingredients_from_palm_oil_tags": [],
        "last_modified_by": "sebleouf",
        "code": "3274080005003",
        "sortkey": 101600699839,
        "traces_hierarchy": [],
        "checked": "on",
        "new_additives_n": 0,
        "brands": "Cristalline",
        "nucleotides_tags": [],
        "interface_version_modified": "20190830",
        "image_front_thumb_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.100.jpg",
        "pnns_groups_1": "Beverages",
        "teams_tags": [
            "stakano",
            "chocolatine"
        ]
    },
    ],
}

product_incomplete = {
    'products': [{
        "product_name_de_debug_tags": [],
        "product_name_en": "Eau Cristaline",
        "generic_name_fr": "Eau de source naturelle",
        "nutrition_grade_fr": "a",
        "data_quality_warnings_tags": [
            "en:nutrition-value-under-0-1-g-salt",
            "en:nutrition-value-very-high-for-category-fat"
        ],
        "minerals_prev_tags": [],
        "url": "https://fr.openfoodfacts.org/produit/3274080005003/eau-de-source-cristalline",
        "image_ingredients_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/ingredients_fr.549.400.jpg",
        "nova_group_tags": [
            "not-applicable"
        ],
        "nutrition_data_prepared_per": "100g",
        "allergens_lc": "fr",
        "amino_acids_tags": [],
        "languages_hierarchy": [
            "en:english",
            "en:french",
            "en:italian"
        ],
        "traces_from_ingredients": "",
        "ingredients_text_with_allergens": "Eau de source.",
        "image_ingredients_small_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/ingredients_fr.549.200.jpg",
        "purchase_places_tags": [
            "france",
            "rennes",
            "chinon",
            "blagnac"
        ],
        "nova_group_debug": "",
        "ingredients_ids_debug": [
            "eau-de-source"
        ],
        "last_checker": "sebleouf",
        "origins_tags": [
            "france"
        ],
        "brands_tags": [
            "cristalline"
        ],
        "labels_hierarchy": [
            "fr:Sans-nitrate"
        ],
        "generic_name_de": "",
        "unique_scans_n": 6482,
        "known_ingredients_n": 2,
        "product_name_it": "Acqua di sorgente",
        "environment_impact_level_tags": [],
        "_id": "3274080005003",
        "nutrition_score_beverage": 1,
        "ingredients_text_fr": "Eau de source.",
        "entry_dates_tags": [
            "2012-07-28",
            "2012-07",
            "2012"
        ],
        "nova_groups_tags": [
            "en:1-unprocessed-or-minimally-processed-foods"
        ],
        "obsolete_since_date": "",
        "ingredients_text_de": "",
        "max_imgid": "313",
        "unknown_ingredients_n": 0,
        "nutrition_grades_tags": [
            "a"
        ],
        "photographers": [],
        "link": "https://www.moneaucristaline.fr/",
        "additives_old_n": 0,
        "ingredients_text": "Eau de source.",
        "nucleotides_prev_tags": [],
        "ingredients": [
            {
                "percent_min": 100,
                "vegan": "yes",
                "vegetarian": "yes",
                "id": "en:spring-water",
                "text": "Eau de source",
                "rank": 1,
                "percent_max": 100
            }
        ],
        "image_front_small_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.200.jpg",
        "ingredients_text_de_debug_tags": [],
        "scans_n": 10501,
        "fruits-vegetables-nuts_100g_estimate": 0,
        "completed_t": 1600699839,
        "update_key": "ingredients3",
        "informers": [
            "sientifix"
        ],
        "checkers_tags": [
            "sebleouf"
        ],
        "misc_tags": [
            "en:nutrition-fruits-vegetables-nuts-estimate-from-ingredients",
            "en:nutrition-all-nutriscore-values-known",
            "en:nutriscore-computed"
        ],
        "product_name_fr": "Eau de source",
        "nutrition_data_prepared": "",
        "ingredients_percent_analysis": 1,
        "countries": "Belgique,France,Allemagne,Guadeloupe,Inde,Italie,Luxembourg,Mali,Martinique,Pays-Bas,Suisse,États-Unis,Royaume-Uni",
        "last_checked_t": 1600699839,
        "emb_codes_orig": "EMB 44068A,EMB 59457",
        "ingredients_from_or_that_may_be_from_palm_oil_n": 0,
        "emb_codes_20141016": "EMB 44068A,EMB 59457",
        "allergens_from_user": "(fr) ",
        "data_quality_bugs_tags": [],
        "emb_codes": "EMB 44068A,EMB 59457,EMB 72007B",
        "generic_name_en": "",
        "ingredients_debug": [
            "Eau de source."
        ],
        "countries_lc": "fr",
        "ingredients_that_may_be_from_palm_oil_tags": [],
        "rev": 593,
        "states": "en:checked, en:complete, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-completed, en:packaging-code-completed, en:characteristics-completed, en:categories-completed, en:brands-completed, en:packaging-completed, en:quantity-completed, en:product-name-completed, en:photos-validated, en:photos-uploaded",
        "ingredients_text_debug": "Eau de source.",
        "nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients_value": 0,
        "unknown_nutrients_tags": [
            "sulfate",
            "nitrate"
        ],
        "last_editor": "sebleouf",
        "expiration_date": "23/10/21",
        "quantity": "1,5 L",
        "labels_lc": "fr",
        "data_sources": "Database - FoodRepo / openfood.ch, Databases, App - labeleat, App - off, App - yuka, Apps",
        "additives_n": 0,
        "image_nutrition_small_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/nutrition_fr.591.200.jpg",
        "data_quality_info_tags": [
            "en:ingredients-percent-analysis-ok"
        ],
        "countries_beforescanbot": "Belgique,France,Allemagne,Guadeloupe,Inde,Italie,Luxembourg,Mali,Martinique,Suisse,États-Unis",
        "ingredients_text_with_allergens_it": "Acqua",
        "packaging": "01 PET,♳,Bouteille,Plastique",
        "popularity_key": 119999996494,
        "nutriments": {
            "nitrate_unit": "mg",
            "silica_unit": "mg",
            "fluoride_100g": 0.0003,
            "silica": 0.026,
            "nutrition-score-fr_100g": 0,
            "chloride_value": 5,
            "fiber": 0,
            "calcium_label": "Calcium",
            "energy-kj_100g": 0,
            "fiber_unit": "g",
            "sulfate_unit": "mg",
            "sulfate_label": "Sulfate",
            "salt": 0.0275,
            "silica_label": "Silice",
            "energy_unit": "kJ",
            "nitrate_value": 1,
            "ph_label": "pH",
            "energy-kj": 0,
            "saturated-fat_unit": "g",
            "bicarbonate_100g": 0.29,
            "potassium_100g": 0.0015,
            "fiber_value": 0,
            "magnesium_100g": 0.025,
            "bicarbonate_unit": "mg",
            "salt_100g": 0.0275,
            "sulfate": 0.006,
            "ph_value": 7.7,
            "calcium_value": 39,
            "chloride_unit": "mg",
            "salt_value": 0.0275,
            "sugars": 0,
            "saturated-fat_100g": 0,
            "fat": 4,
            "nitrate_label": "Nitrate",
            "energy_100g": 0,
            "nutrition-score-fr": 0,
            "potassium_unit": "mg",
            "nova-group": 1,
            "sodium": 0.011,
            "sodium_unit": "g",
            "energy-kcal_100g": 0,
            "bicarbonate_label": "Bicarbonate",
            "nova-group_serving": 1,
            "ph": 7.7,
            "fluoride": 0.0003,
            "carbohydrates_value": 0,
            "nitrate_100g": 0.001,
            "chloride": 0.005,
            "calcium_100g": 0.039,
            "nitrate": 0.001,
            "carbohydrates": 0,
            "fiber_100g": 0,
            "bicarbonate": 0.29,
            "fluoride_value": 0.3,
            "carbohydrates_unit": "g",
            "sulfate_100g": 0.006,
            "sodium_100g": 0.011,
            "proteins": 0,
            "proteins_100g": 0,
            "energy-kcal_value": 0,
            "sugars_unit": "g",
            "calcium": 0.039,
            "calcium_unit": "mg",
            "silica_100g": 0.026,
            "energy-kcal": 0,
            "carbohydrates_100g": 0,
            "ph_serving": 7.7,
            "sodium_value": 0.011,
            "silica_value": 26,
            "chloride_100g": 0.005,
            "energy-kj_unit": "kJ",
            "salt_unit": "g",
            "energy-kcal_unit": "kcal",
            "potassium": 0.0015,
            "sugars_value": 0,
            "fluoride_unit": "mg",
            "potassium_value": 1.5,
            "proteins_value": 0,
            "bicarbonate_value": 290,
            "fat_value": 4,
            "magnesium_unit": "mg",
            "fat_unit": "g",
            "saturated-fat_value": 0,
            "sugars_100g": 0,
            "proteins_unit": "g",
            "sulfate_value": 6,
            "magnesium_value": 25,
            "energy-kj_value": 0,
            "fluoride_label": "Fluor",
            "ph_100g": 7.7,
            "fat_100g": 4,
            "saturated-fat": 0,
            "fruits-vegetables-nuts-estimate-from-ingredients_100g": 0,
            "energy_value": 0,
            "magnesium_label": "Magnésium",
            "nova-group_100g": 1,
            "energy": 0,
            "ph_unit": "g",
            "magnesium": 0.025,
            "potassium_label": "Potassium",
            "chloride_label": "Chlorure"
        },
        "nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients": 1,
        "category_properties": {
            "ciqual_food_name:en": "Spring still water -Cristaline-, bottled",
            "ciqual_food_name:fr": "Eau de source Cristaline, embouteillée, non gazeuse"
        },
        "categories_lc": "fr",
        "stores": "Carrefour,auchan,Leclerc",
        "ingredients_text_en": "water",
        "image_thumb_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.100.jpg",
        "data_quality_tags": [
            "en:ingredients-percent-analysis-ok",
            "en:nutrition-value-under-0-1-g-salt",
            "en:nutrition-value-very-high-for-category-fat"
        ],
        "traces_from_user": "(fr) ",
        "checkers": [],
        "additives_old_tags": [],
        "vitamins_tags": [],
        "ingredients_hierarchy": [
            "en:spring-water",
            "en:water"
        ],
        "categories": "Boissons, Eaux, Eaux de sources, Eaux minérales, Boissons sans sucre ajouté",
        "no_nutrition_data": "",
        "pnns_groups_1_tags": [
            "beverages",
            "known"
        ],
        "additives_original_tags": [],
        "other_nutritional_substances_tags": [],
        "ingredients_tags": [
            "en:spring-water",
            "en:water"
        ],
        "purchase_places": "France,Rennes,Chinon,Blagnac",
        "compared_to_category": "en:unsweetened-beverages",
        "created_t": 1343503270,
        "lang": "fr",
        "cities_tags": [
            "guenrouet-loire-atlantique-france",
            "perenchies-nord-france",
            "ardenay-sur-merize-sarthe-france"
        ],
        "pnns_groups_2_tags": [
            "waters-and-flavored-waters",
            "known"
        ],
        "environment_impact_level": "",
        "nutrition_data_per": "100g",
        "ingredients_from_palm_oil_n": 0,
        "product_name_de": "",
        "allergens_from_ingredients": "",
        "labels_tags": [
            "fr:sans-nitrate"
        ],
        "image_ingredients_thumb_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/ingredients_fr.549.100.jpg",
        "amino_acids_prev_tags": [],
        "origins": "France",
        "allergens_hierarchy": [],
        "generic_name": "Eau de source naturelle",
        "image_nutrition_thumb_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/nutrition_fr.591.100.jpg",
        "lc": "fr",
        "complete": 0,
        "generic_name_it": "Acqua minerale",
        "ingredients_text_it": "Acqua",
        "ingredients_that_may_be_from_palm_oil_n": 0,
        "data_quality_errors_tags": [],
        "interface_version_created": "20120622",
        "labels": "Sans-nitrate",
        "completeness": 1,
        "image_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.400.jpg",
        "traces": "",
        "correctors": [],
        "vitamins_prev_tags": [],
        "ingredients_n": 1,
        "additives_debug_tags": [],
        "manufacturing_places": "France,72370,Ardenay-sur-Merize",
        "nova_group": 1,
        "image_small_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.200.jpg",
        "emb_codes_tags": [
            "emb-44068a",
            "emb-59457",
            "emb-72007b"
        ],
        "id": "3274080005003",
        "stores_tags": [
            "carrefour",
            "auchan",
            "leclerc"
        ],
        "debug_tags": [
            "43"
        ],
        "nutriscore_score": 0,
        "nutrition_data": "on",
        "traces_lc": "fr",
        "image_nutrition_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/nutrition_fr.591.400.jpg",
        "image_front_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.400.jpg",
        "ingredients_text_with_allergens_fr": "Eau de source.",
        "nutriscore_grade": "a",
        "languages": {
            "en:english": 4,
            "en:french": 6,
            "en:italian": 5
        },
        "last_edit_dates_tags": [
            "2020-09-21",
            "2020-09",
            "2020"
        ],
        "nutrient_levels_tags": [
            "en:fat-in-moderate-quantity",
            "en:saturated-fat-in-low-quantity",
            "en:sugars-in-low-quantity",
            "en:salt-in-low-quantity"
        ],
        "minerals_tags": [],
        "ingredients_text_with_allergens_en": "water",
        "allergens": "",
        "obsolete": "",
        "ingredients_original_tags": [
            "en:spring-water"
        ],
        "generic_name_de_debug_tags": [],
        "product_name": "Eau de source",
        "nutrition_grades": "a",
        "last_image_t": 1598513295,
        "additives_tags": [],
        "ingredients_from_palm_oil_tags": [],
        "last_modified_by": "sebleouf",
        "code": "3274080005003",
        "sortkey": 101600699839,
        "traces_hierarchy": [],
        "checked": "on",
        "new_additives_n": 0,
        "brands": "Cristalline",
        "nucleotides_tags": [],
        "interface_version_modified": "20190830",
        "image_front_thumb_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.100.jpg",
        "pnns_groups_1": "Beverages",
        "teams_tags": [
            "stakano",
            "chocolatine"
        ]
    },
    ],
}

product_key_missing = {
    'products': [{
        "product_name_de_debug_tags": [],
        "product_name_en": "Eau Cristaline",
        "generic_name_fr": "Eau de source naturelle",
        "nutrition_grade_fr": "a",
        "data_quality_warnings_tags": [
            "en:nutrition-value-under-0-1-g-salt",
            "en:nutrition-value-very-high-for-category-fat"
        ],
        "minerals_prev_tags": [],
        "url": "https://fr.openfoodfacts.org/produit/3274080005003/eau-de-source-cristalline",
        "image_ingredients_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/ingredients_fr.549.400.jpg",
        "nova_group_tags": [
            "not-applicable"
        ],
        "nutrition_data_prepared_per": "100g",
        "allergens_lc": "fr",
        "amino_acids_tags": [],
        "languages_hierarchy": [
            "en:english",
            "en:french",
            "en:italian"
        ],
        "traces_from_ingredients": "",
        "ingredients_text_with_allergens": "Eau de source.",
        "image_ingredients_small_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/ingredients_fr.549.200.jpg",
        "purchase_places_tags": [
            "france",
            "rennes",
            "chinon",
            "blagnac"
        ],
        "nova_group_debug": "",
        "ingredients_ids_debug": [
            "eau-de-source"
        ],
        "last_checker": "sebleouf",
        "origins_tags": [
            "france"
        ],
        "brands_tags": [
            "cristalline"
        ],
        "labels_hierarchy": [
            "fr:Sans-nitrate"
        ],
        "generic_name_de": "",
        "unique_scans_n": 6482,
        "known_ingredients_n": 2,
        "product_name_it": "Acqua di sorgente",
        "environment_impact_level_tags": [],
        "_id": "3274080005003",
        "nutrition_score_beverage": 1,
        "ingredients_text_fr": "Eau de source.",
        "entry_dates_tags": [
            "2012-07-28",
            "2012-07",
            "2012"
        ],
        "nova_groups_tags": [
            "en:1-unprocessed-or-minimally-processed-foods"
        ],
        "obsolete_since_date": "",
        "ingredients_text_de": "",
        "max_imgid": "313",
        "unknown_ingredients_n": 0,
        "nutrition_grades_tags": [
            "a"
        ],
        "photographers": [],
        "link": "https://www.moneaucristaline.fr/",
        "additives_old_n": 0,
        "ingredients_text": "Eau de source.",
        "nucleotides_prev_tags": [],
        "ingredients": [
            {
                "percent_min": 100,
                "vegan": "yes",
                "vegetarian": "yes",
                "id": "en:spring-water",
                "text": "Eau de source",
                "rank": 1,
                "percent_max": 100
            }
        ],
        "image_front_small_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.200.jpg",
        "ingredients_text_de_debug_tags": [],
        "scans_n": 10501,
        "fruits-vegetables-nuts_100g_estimate": 0,
        "completed_t": 1600699839,
        "update_key": "ingredients3",
        "informers": [
            "sientifix"
        ],
        "checkers_tags": [
            "sebleouf"
        ],
        "misc_tags": [
            "en:nutrition-fruits-vegetables-nuts-estimate-from-ingredients",
            "en:nutrition-all-nutriscore-values-known",
            "en:nutriscore-computed"
        ],
        "nutrition_data_prepared": "",
        "ingredients_percent_analysis": 1,
        "countries": "Belgique,France,Allemagne,Guadeloupe,Inde,Italie,Luxembourg,Mali,Martinique,Pays-Bas,Suisse,États-Unis,Royaume-Uni",
        "last_checked_t": 1600699839,
        "emb_codes_orig": "EMB 44068A,EMB 59457",
        "ingredients_from_or_that_may_be_from_palm_oil_n": 0,
        "emb_codes_20141016": "EMB 44068A,EMB 59457",
        "allergens_from_user": "(fr) ",
        "data_quality_bugs_tags": [],
        "emb_codes": "EMB 44068A,EMB 59457,EMB 72007B",
        "generic_name_en": "",
        "ingredients_debug": [
            "Eau de source."
        ],
        "countries_lc": "fr",
        "ingredients_that_may_be_from_palm_oil_tags": [],
        "rev": 593,
        "states": "en:checked, en:complete, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-completed, en:packaging-code-completed, en:characteristics-completed, en:categories-completed, en:brands-completed, en:packaging-completed, en:quantity-completed, en:product-name-completed, en:photos-validated, en:photos-uploaded",
        "ingredients_text_debug": "Eau de source.",
        "nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients_value": 0,
        "unknown_nutrients_tags": [
            "sulfate",
            "nitrate"
        ],
        "last_editor": "sebleouf",
        "expiration_date": "23/10/21",
        "quantity": "1,5 L",
        "labels_lc": "fr",
        "data_sources": "Database - FoodRepo / openfood.ch, Databases, App - labeleat, App - off, App - yuka, Apps",
        "additives_n": 0,
        "image_nutrition_small_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/nutrition_fr.591.200.jpg",
        "data_quality_info_tags": [
            "en:ingredients-percent-analysis-ok"
        ],
        "countries_beforescanbot": "Belgique,France,Allemagne,Guadeloupe,Inde,Italie,Luxembourg,Mali,Martinique,Suisse,États-Unis",
        "ingredients_text_with_allergens_it": "Acqua",
        "packaging": "01 PET,♳,Bouteille,Plastique",
        "popularity_key": 119999996494,
        "nutriments": {
            "nitrate_unit": "mg",
            "silica_unit": "mg",
            "fluoride_100g": 0.0003,
            "silica": 0.026,
            "nutrition-score-fr_100g": 0,
            "chloride_value": 5,
            "fiber": 0,
            "calcium_label": "Calcium",
            "energy-kj_100g": 0,
            "fiber_unit": "g",
            "sulfate_unit": "mg",
            "sulfate_label": "Sulfate",
            "salt": 0.0275,
            "silica_label": "Silice",
            "energy_unit": "kJ",
            "nitrate_value": 1,
            "ph_label": "pH",
            "energy-kj": 0,
            "saturated-fat_unit": "g",
            "bicarbonate_100g": 0.29,
            "potassium_100g": 0.0015,
            "fiber_value": 0,
            "magnesium_100g": 0.025,
            "bicarbonate_unit": "mg",
            "salt_100g": 0.0275,
            "sulfate": 0.006,
            "ph_value": 7.7,
            "calcium_value": 39,
            "chloride_unit": "mg",
            "salt_value": 0.0275,
            "sugars": 0,
            "saturated-fat_100g": 0,
            "fat": 4,
            "nitrate_label": "Nitrate",
            "energy_100g": 0,
            "nutrition-score-fr": 0,
            "potassium_unit": "mg",
            "nova-group": 1,
            "sodium": 0.011,
            "sodium_unit": "g",
            "energy-kcal_100g": 0,
            "bicarbonate_label": "Bicarbonate",
            "nova-group_serving": 1,
            "ph": 7.7,
            "fluoride": 0.0003,
            "carbohydrates_value": 0,
            "nitrate_100g": 0.001,
            "chloride": 0.005,
            "calcium_100g": 0.039,
            "nitrate": 0.001,
            "carbohydrates": 0,
            "fiber_100g": 0,
            "bicarbonate": 0.29,
            "fluoride_value": 0.3,
            "carbohydrates_unit": "g",
            "sulfate_100g": 0.006,
            "sodium_100g": 0.011,
            "proteins": 0,
            "proteins_100g": 0,
            "energy-kcal_value": 0,
            "sugars_unit": "g",
            "calcium": 0.039,
            "calcium_unit": "mg",
            "silica_100g": 0.026,
            "energy-kcal": 0,
            "carbohydrates_100g": 0,
            "ph_serving": 7.7,
            "sodium_value": 0.011,
            "silica_value": 26,
            "chloride_100g": 0.005,
            "energy-kj_unit": "kJ",
            "salt_unit": "g",
            "energy-kcal_unit": "kcal",
            "potassium": 0.0015,
            "sugars_value": 0,
            "fluoride_unit": "mg",
            "potassium_value": 1.5,
            "proteins_value": 0,
            "bicarbonate_value": 290,
            "fat_value": 4,
            "magnesium_unit": "mg",
            "fat_unit": "g",
            "saturated-fat_value": 0,
            "sugars_100g": 0,
            "proteins_unit": "g",
            "sulfate_value": 6,
            "magnesium_value": 25,
            "energy-kj_value": 0,
            "fluoride_label": "Fluor",
            "ph_100g": 7.7,
            "fat_100g": 4,
            "saturated-fat": 0,
            "fruits-vegetables-nuts-estimate-from-ingredients_100g": 0,
            "energy_value": 0,
            "magnesium_label": "Magnésium",
            "nova-group_100g": 1,
            "energy": 0,
            "ph_unit": "g",
            "magnesium": 0.025,
            "potassium_label": "Potassium",
            "chloride_label": "Chlorure"
        },
        "nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients": 1,
        "category_properties": {
            "ciqual_food_name:en": "Spring still water -Cristaline-, bottled",
            "ciqual_food_name:fr": "Eau de source Cristaline, embouteillée, non gazeuse"
        },
        "categories_lc": "fr",
        "stores": "Carrefour,auchan,Leclerc",
        "ingredients_text_en": "water",
        "image_thumb_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.100.jpg",
        "data_quality_tags": [
            "en:ingredients-percent-analysis-ok",
            "en:nutrition-value-under-0-1-g-salt",
            "en:nutrition-value-very-high-for-category-fat"
        ],
        "traces_from_user": "(fr) ",
        "checkers": [],
        "additives_old_tags": [],
        "vitamins_tags": [],
        "ingredients_hierarchy": [
            "en:spring-water",
            "en:water"
        ],
        "categories": "Boissons, Eaux, Eaux de sources, Eaux minérales, Boissons sans sucre ajouté",
        "no_nutrition_data": "",
        "pnns_groups_1_tags": [
            "beverages",
            "known"
        ],
        "additives_original_tags": [],
        "other_nutritional_substances_tags": [],
        "ingredients_tags": [
            "en:spring-water",
            "en:water"
        ],
        "purchase_places": "France,Rennes,Chinon,Blagnac",
        "compared_to_category": "en:unsweetened-beverages",
        "created_t": 1343503270,
        "lang": "fr",
        "cities_tags": [
            "guenrouet-loire-atlantique-france",
            "perenchies-nord-france",
            "ardenay-sur-merize-sarthe-france"
        ],
        "pnns_groups_2_tags": [
            "waters-and-flavored-waters",
            "known"
        ],
        "environment_impact_level": "",
        "nutrition_data_per": "100g",
        "ingredients_from_palm_oil_n": 0,
        "product_name_de": "",
        "allergens_from_ingredients": "",
        "labels_tags": [
            "fr:sans-nitrate"
        ],
        "image_ingredients_thumb_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/ingredients_fr.549.100.jpg",
        "amino_acids_prev_tags": [],
        "origins": "France",
        "allergens_hierarchy": [],
        "generic_name": "Eau de source naturelle",
        "image_nutrition_thumb_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/nutrition_fr.591.100.jpg",
        "lc": "fr",
        "complete": 1,
        "generic_name_it": "Acqua minerale",
        "ingredients_text_it": "Acqua",
        "ingredients_that_may_be_from_palm_oil_n": 0,
        "data_quality_errors_tags": [],
        "interface_version_created": "20120622",
        "labels": "Sans-nitrate",
        "completeness": 1,
        "image_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.400.jpg",
        "traces": "",
        "correctors": [],
        "vitamins_prev_tags": [],
        "ingredients_n": 1,
        "additives_debug_tags": [],
        "manufacturing_places": "France,72370,Ardenay-sur-Merize",
        "nova_group": 1,
        "image_small_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.200.jpg",
        "emb_codes_tags": [
            "emb-44068a",
            "emb-59457",
            "emb-72007b"
        ],
        "id": "3274080005003",
        "stores_tags": [
            "carrefour",
            "auchan",
            "leclerc"
        ],
        "debug_tags": [
            "43"
        ],
        "nutriscore_score": 0,
        "nutrition_data": "on",
        "traces_lc": "fr",
        "image_nutrition_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/nutrition_fr.591.400.jpg",
        "image_front_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.400.jpg",
        "ingredients_text_with_allergens_fr": "Eau de source.",
        "nutriscore_grade": "a",
        "languages": {
            "en:english": 4,
            "en:french": 6,
            "en:italian": 5
        },
        "last_edit_dates_tags": [
            "2020-09-21",
            "2020-09",
            "2020"
        ],
        "nutrient_levels_tags": [
            "en:fat-in-moderate-quantity",
            "en:saturated-fat-in-low-quantity",
            "en:sugars-in-low-quantity",
            "en:salt-in-low-quantity"
        ],
        "minerals_tags": [],
        "ingredients_text_with_allergens_en": "water",
        "allergens": "",
        "obsolete": "",
        "ingredients_original_tags": [
            "en:spring-water"
        ],
        "generic_name_de_debug_tags": [],
        "product_name": "Eau de source",
        "nutrition_grades": "a",
        "last_image_t": 1598513295,
        "additives_tags": [],
        "ingredients_from_palm_oil_tags": [],
        "last_modified_by": "sebleouf",
        "code": "3274080005003",
        "sortkey": 101600699839,
        "traces_hierarchy": [],
        "checked": "on",
        "new_additives_n": 0,
        "brands": "Cristalline",
        "nucleotides_tags": [],
        "interface_version_modified": "20190830",
        "image_front_thumb_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.100.jpg",
        "pnns_groups_1": "Beverages",
        "teams_tags": [
            "stakano",
            "chocolatine"
        ]
    },
    ],
}

product_with_none_nutriments = {
    'products': [{
        "product_name_de_debug_tags": [],
        "product_name_en": "Eau Cristaline",
        "generic_name_fr": "Eau de source naturelle",
        "nutrition_grade_fr": "a",
        "data_quality_warnings_tags": [
            "en:nutrition-value-under-0-1-g-salt",
            "en:nutrition-value-very-high-for-category-fat"
        ],
        "minerals_prev_tags": [],
        "url": "https://fr.openfoodfacts.org/produit/3274080005003/eau-de-source-cristalline",
        "image_ingredients_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/ingredients_fr.549.400.jpg",
        "nova_group_tags": [
            "not-applicable"
        ],
        "nutrition_data_prepared_per": "100g",
        "allergens_lc": "fr",
        "amino_acids_tags": [],
        "languages_hierarchy": [
            "en:english",
            "en:french",
            "en:italian"
        ],
        "traces_from_ingredients": "",
        "ingredients_text_with_allergens": "Eau de source.",
        "image_ingredients_small_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/ingredients_fr.549.200.jpg",
        "purchase_places_tags": [
            "france",
            "rennes",
            "chinon",
            "blagnac"
        ],
        "nova_group_debug": "",
        "ingredients_ids_debug": [
            "eau-de-source"
        ],
        "last_checker": "sebleouf",
        "origins_tags": [
            "france"
        ],
        "brands_tags": [
            "cristalline"
        ],
        "labels_hierarchy": [
            "fr:Sans-nitrate"
        ],
        "generic_name_de": "",
        "unique_scans_n": 6482,
        "known_ingredients_n": 2,
        "product_name_it": "Acqua di sorgente",
        "environment_impact_level_tags": [],
        "_id": "3274080005003",
        "nutrition_score_beverage": 1,
        "ingredients_text_fr": "Eau de source.",
        "entry_dates_tags": [
            "2012-07-28",
            "2012-07",
            "2012"
        ],
        "nova_groups_tags": [
            "en:1-unprocessed-or-minimally-processed-foods"
        ],
        "obsolete_since_date": "",
        "ingredients_text_de": "",
        "max_imgid": "313",
        "unknown_ingredients_n": 0,
        "nutrition_grades_tags": [
            "a"
        ],
        "photographers": [],
        "link": "https://www.moneaucristaline.fr/",
        "additives_old_n": 0,
        "ingredients_text": "Eau de source.",
        "nucleotides_prev_tags": [],
        "ingredients": [
            {
                "percent_min": 100,
                "vegan": "yes",
                "vegetarian": "yes",
                "id": "en:spring-water",
                "text": "Eau de source",
                "rank": 1,
                "percent_max": 100
            }
        ],
        "image_front_small_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.200.jpg",
        "ingredients_text_de_debug_tags": [],
        "scans_n": 10501,
        "fruits-vegetables-nuts_100g_estimate": 0,
        "completed_t": 1600699839,
        "update_key": "ingredients3",
        "informers": [
            "sientifix"
        ],
        "checkers_tags": [
            "sebleouf"
        ],
        "misc_tags": [
            "en:nutrition-fruits-vegetables-nuts-estimate-from-ingredients",
            "en:nutrition-all-nutriscore-values-known",
            "en:nutriscore-computed"
        ],
        "product_name_fr": "Eau de source",
        "nutrition_data_prepared": "",
        "ingredients_percent_analysis": 1,
        "countries": "Belgique,France,Allemagne,Guadeloupe,Inde,Italie,Luxembourg,Mali,Martinique,Pays-Bas,Suisse,États-Unis,Royaume-Uni",
        "last_checked_t": 1600699839,
        "emb_codes_orig": "EMB 44068A,EMB 59457",
        "ingredients_from_or_that_may_be_from_palm_oil_n": 0,
        "emb_codes_20141016": "EMB 44068A,EMB 59457",
        "allergens_from_user": "(fr) ",
        "data_quality_bugs_tags": [],
        "emb_codes": "EMB 44068A,EMB 59457,EMB 72007B",
        "generic_name_en": "",
        "ingredients_debug": [
            "Eau de source."
        ],
        "countries_lc": "fr",
        "ingredients_that_may_be_from_palm_oil_tags": [],
        "rev": 593,
        "states": "en:checked, en:complete, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-completed, en:packaging-code-completed, en:characteristics-completed, en:categories-completed, en:brands-completed, en:packaging-completed, en:quantity-completed, en:product-name-completed, en:photos-validated, en:photos-uploaded",
        "ingredients_text_debug": "Eau de source.",
        "nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients_value": 0,
        "unknown_nutrients_tags": [
            "sulfate",
            "nitrate"
        ],
        "last_editor": "sebleouf",
        "expiration_date": "23/10/21",
        "quantity": "1,5 L",
        "labels_lc": "fr",
        "data_sources": "Database - FoodRepo / openfood.ch, Databases, App - labeleat, App - off, App - yuka, Apps",
        "additives_n": 0,
        "image_nutrition_small_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/nutrition_fr.591.200.jpg",
        "data_quality_info_tags": [
            "en:ingredients-percent-analysis-ok"
        ],
        "countries_beforescanbot": "Belgique,France,Allemagne,Guadeloupe,Inde,Italie,Luxembourg,Mali,Martinique,Suisse,États-Unis",
        "ingredients_text_with_allergens_it": "Acqua",
        "packaging": "01 PET,♳,Bouteille,Plastique",
        "popularity_key": 119999996494,
        "nutriments": {
            "nitrate_unit": "mg",
            "silica_unit": "mg",
            "fluoride_100g": 0.0003,
            "silica": 0.026,
            "nutrition-score-fr_100g": 0,
            "chloride_value": 5,
            "fiber": 0,
            "calcium_label": "Calcium",
            "energy-kj_100g": 0,
            "fiber_unit": "g",
            "sulfate_unit": "mg",
            "sulfate_label": "Sulfate",
            "salt": 0.0275,
            "silica_label": "Silice",
            "energy_unit": "kJ",
            "nitrate_value": 1,
            "ph_label": "pH",
            "energy-kj": 0,
            "saturated-fat_unit": "g",
            "bicarbonate_100g": 0.29,
            "potassium_100g": 0.0015,
            "fiber_value": 0,
            "magnesium_100g": 0.025,
            "bicarbonate_unit": "mg",
            # "salt_100g": 0.0275,
            "sulfate": 0.006,
            "ph_value": 7.7,
            "calcium_value": 39,
            "chloride_unit": "mg",
            "salt_value": 0.0275,
            "sugars": 0,
            "saturated-fat_100g": 0,
            "fat": 4,
            "nitrate_label": "Nitrate",
            "energy_100g": 0,
            "nutrition-score-fr": 0,
            "potassium_unit": "mg",
            "nova-group": 1,
            "sodium": 0.011,
            "sodium_unit": "g",
            "energy-kcal_100g": 0,
            "bicarbonate_label": "Bicarbonate",
            "nova-group_serving": 1,
            "ph": 7.7,
            "fluoride": 0.0003,
            "carbohydrates_value": 0,
            "nitrate_100g": 0.001,
            "chloride": 0.005,
            "calcium_100g": 0.039,
            "nitrate": 0.001,
            "carbohydrates": 0,
            # "fiber_100g": 0,
            "bicarbonate": 0.29,
            "fluoride_value": 0.3,
            "carbohydrates_unit": "g",
            "sulfate_100g": 0.006,
            "sodium_100g": 0.011,
            "proteins": 0,
            "proteins_100g": 0,
            "energy-kcal_value": 0,
            "sugars_unit": "g",
            "calcium": 0.039,
            "calcium_unit": "mg",
            "silica_100g": 0.026,
            "energy-kcal": 0,
            "carbohydrates_100g": 0,
            "ph_serving": 7.7,
            "sodium_value": 0.011,
            "silica_value": 26,
            "chloride_100g": 0.005,
            "energy-kj_unit": "kJ",
            "salt_unit": "g",
            "energy-kcal_unit": "kcal",
            "potassium": 0.0015,
            "sugars_value": 0,
            "fluoride_unit": "mg",
            "potassium_value": 1.5,
            "proteins_value": 0,
            "bicarbonate_value": 290,
            "fat_value": 4,
            "magnesium_unit": "mg",
            "fat_unit": "g",
            "saturated-fat_value": 0,
            "sugars_100g": 0,
            "proteins_unit": "g",
            "sulfate_value": 6,
            "magnesium_value": 25,
            "energy-kj_value": 0,
            "fluoride_label": "Fluor",
            "ph_100g": 7.7,
            "fat_100g": 4,
            "saturated-fat": 0,
            "fruits-vegetables-nuts-estimate-from-ingredients_100g": 0,
            "energy_value": 0,
            "magnesium_label": "Magnésium",
            "nova-group_100g": 1,
            "energy": 0,
            "ph_unit": "g",
            "magnesium": 0.025,
            "potassium_label": "Potassium",
            "chloride_label": "Chlorure"
        },
        "nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients": 1,
        "category_properties": {
            "ciqual_food_name:en": "Spring still water -Cristaline-, bottled",
            "ciqual_food_name:fr": "Eau de source Cristaline, embouteillée, non gazeuse"
        },
        "categories_lc": "fr",
        "stores": "Carrefour,auchan,Leclerc",
        "ingredients_text_en": "water",
        "image_thumb_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.100.jpg",
        "data_quality_tags": [
            "en:ingredients-percent-analysis-ok",
            "en:nutrition-value-under-0-1-g-salt",
            "en:nutrition-value-very-high-for-category-fat"
        ],
        "traces_from_user": "(fr) ",
        "checkers": [],
        "additives_old_tags": [],
        "vitamins_tags": [],
        "ingredients_hierarchy": [
            "en:spring-water",
            "en:water"
        ],
        "categories": "Boissons, Eaux, Eaux de sources, Eaux minérales, Boissons sans sucre ajouté",
        "no_nutrition_data": "",
        "pnns_groups_1_tags": [
            "beverages",
            "known"
        ],
        "additives_original_tags": [],
        "other_nutritional_substances_tags": [],
        "ingredients_tags": [
            "en:spring-water",
            "en:water"
        ],
        "purchase_places": "France,Rennes,Chinon,Blagnac",
        "compared_to_category": "en:unsweetened-beverages",
        "created_t": 1343503270,
        "lang": "fr",
        "cities_tags": [
            "guenrouet-loire-atlantique-france",
            "perenchies-nord-france",
            "ardenay-sur-merize-sarthe-france"
        ],
        "pnns_groups_2_tags": [
            "waters-and-flavored-waters",
            "known"
        ],
        "environment_impact_level": "",
        "nutrition_data_per": "100g",
        "ingredients_from_palm_oil_n": 0,
        "product_name_de": "",
        "allergens_from_ingredients": "",
        "labels_tags": [
            "fr:sans-nitrate"
        ],
        "image_ingredients_thumb_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/ingredients_fr.549.100.jpg",
        "amino_acids_prev_tags": [],
        "origins": "France",
        "allergens_hierarchy": [],
        "generic_name": "Eau de source naturelle",
        "image_nutrition_thumb_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/nutrition_fr.591.100.jpg",
        "lc": "fr",
        "complete": 1,
        "generic_name_it": "Acqua minerale",
        "ingredients_text_it": "Acqua",
        "ingredients_that_may_be_from_palm_oil_n": 0,
        "data_quality_errors_tags": [],
        "interface_version_created": "20120622",
        "labels": "Sans-nitrate",
        "completeness": 1,
        "image_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.400.jpg",
        "traces": "",
        "correctors": [],
        "vitamins_prev_tags": [],
        "ingredients_n": 1,
        "additives_debug_tags": [],
        "manufacturing_places": "France,72370,Ardenay-sur-Merize",
        "nova_group": 1,
        "image_small_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.200.jpg",
        "emb_codes_tags": [
            "emb-44068a",
            "emb-59457",
            "emb-72007b"
        ],
        "id": "3274080005003",
        "stores_tags": [
            "carrefour",
            "auchan",
            "leclerc"
        ],
        "debug_tags": [
            "43"
        ],
        "nutriscore_score": 0,
        "nutrition_data": "on",
        "traces_lc": "fr",
        "image_nutrition_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/nutrition_fr.591.400.jpg",
        "image_front_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.400.jpg",
        "ingredients_text_with_allergens_fr": "Eau de source.",
        "nutriscore_grade": "a",
        "languages": {
            "en:english": 4,
            "en:french": 6,
            "en:italian": 5
        },
        "last_edit_dates_tags": [
            "2020-09-21",
            "2020-09",
            "2020"
        ],
        "nutrient_levels_tags": [
            "en:fat-in-moderate-quantity",
            "en:saturated-fat-in-low-quantity",
            "en:sugars-in-low-quantity",
            "en:salt-in-low-quantity"
        ],
        "minerals_tags": [],
        "ingredients_text_with_allergens_en": "water",
        "allergens": "",
        "obsolete": "",
        "ingredients_original_tags": [
            "en:spring-water"
        ],
        "generic_name_de_debug_tags": [],
        "product_name": "Eau de source",
        "nutrition_grades": "a",
        "last_image_t": 1598513295,
        "additives_tags": [],
        "ingredients_from_palm_oil_tags": [],
        "last_modified_by": "sebleouf",
        "code": "3274080005003",
        "sortkey": 101600699839,
        "traces_hierarchy": [],
        "checked": "on",
        "new_additives_n": 0,
        "brands": "Cristalline",
        "nucleotides_tags": [],
        "interface_version_modified": "20190830",
        "image_front_thumb_url": "https://static.openfoodfacts.org/images/products/327/408/000/5003/front_fr.556.100.jpg",
        "pnns_groups_1": "Beverages",
        "teams_tags": [
            "stakano",
            "chocolatine"
        ]
    },
    ],
}
